# -*- coding: utf-8 -*-
"""[爬蟲]大盤櫃買總市值.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NrHHsOYO0GYwysAb7ngi79bCTzn2c0JY
"""

!pip install yfinance
!pip install h5py

# import yfinance抓每日大盤,櫃買,台積電股價
import yfinance as yf
import h5py
import pandas as pd

# 爬大盤
stock_id = '^TWII'
data = yf.Ticker(stock_id)
df = data.history(start="2010-01-01", end="2021-09-30")

# 爬櫃買
stock_id1 = '^TWOII'
data = yf.Ticker(stock_id1)
df1 = data.history(start="2010-01-01", end="2021-09-30")

# 爬台積電
stock_id1 = '2330.TW'
data = yf.Ticker(stock_id1)
df2 = data.history(start="2010-01-01", end="2021-09-31")

# 合併大盤,櫃買,台積電股價 by日期
df4=df.merge(df1, how='left', on='Date',suffixes=('_twii', '_twoii'))

df4=df4.merge(df2['Close'], how='left', on='Date')

'''
!pip install yahoo_fin
import yahoo_fin.stock_info as si
# 抓台積電市值(但只能抓到當天所以放棄)
si.get_quote_table("2330.TW")["Market Cap"]
'''



## 計算大盤扣除台積電
# 載入大盤市值csv
from google.colab import files
uploaded = files.upload()

mc1=pd.read_csv('part1.csv')

mc1=mc1.drop(columns=['(由2005/09/02起資料)','Unnamed: 3','Unnamed: 4'])
mc1.columns = ['Date', 'marketCap']

mc1['Date']=mc1['Date'].replace({"/":'-'}, regex=True)

mc1.Date[mc1.Date == "2010-01-08"].index.tolist()

mc1=mc1.drop(mc1.index[0:223])

#df2.index = df2.index.map(str)
mc1.Date=mc1.Date.astype('datetime64[ns]')
#mc1.set_index('Date')

mc1=mc1.set_index('Date')

#df2.index=df2.index.replace({"00:00:00":''}, regex=True)

df3=df2.merge(mc1, how='left', on='Date')

df3['marketCap']=df3['marketCap'].bfill(axis ='rows')

from google.colab import  drive
drive.mount('/drive')

df3.to_csv('twii.csv')
!cp twii.csv "/drive/My Drive/Colab Notebooks/"

